apiVersion: v2
name: metrics-server
description: A Helm chart for Kubernetes Metrics Server
type: application
version: 0.1.0
appVersion: "0.7.2"
keywords:
  - metrics
  - monitoring
  - kubernetes
maintainers:
  - name: ecoutu
