blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/ecoutu/kubernetes-stack/discussions
    about: Ask questions or discuss ideas in GitHub Discussions
